### ISSUE TITLE
Plik apk do pobrania

### ISSUE THREAD

**Issue by J4CKED** [otwarty-wykop-mobilny/wykop-android#205]
Proszę dodać możliwość pobrania pliku apk.

**Comment by mateuszkwiecinski** [comment]
Ogólnie to nie będzie takie łatwe. Aplikacja publikowana jest w formie [App Bundle](https://developer.android.com/guide/app-bundle) zgodnie z wymaganiami sklepu Google Play — co oznacza, że apk jest składane po stronie Googla i klucz do podpisywania jest używany i trzymany również po stronie Googla. To powoduje, ze lokalnie nie jestem w stanie zbudować _kompatybilnego_ apk, które mogłoby być używane wymiennie z tymi generowanymi przez sklep. System będzie uznawał je za inne aplikacje.

Możesz opisać swój use case? Korzystasz z jakiegoś innego sklepu niż Google Play?

**Comment by mateuszkwiecinski** [comment]
Fixed in #206 
Apk powinno byc pobieralne ze strony z releasem: https://github.com/otwarty-wykop-mobilny/wykop-android/releases/latest (osobiście nie testowałem czy wszystko dziala, ale powinno 😬)

Jest podpisane innym kluczem wiec jeżeli masz zainstalowaną starą wersję, to system będzie krzyczał, że to jest inna aplikacja.

**Comment by J4CKED** [comment]
Dobra robota. Później przetestuję.
